import {
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  Client,
  DiscordAPIError,
  EmbedBuilder,
  Events,
  MessageFlags,
  PermissionsBitField,
  type APIEmbedField,
  type ButtonInteraction,
  type ChatInputCommandInteraction,
  type ClientOptions,
  type GuildMember,
  type User,
} from 'discord.js';
import { randomUUID } from 'node:crypto';
import { loadEnv, resetEnvCache, type Env } from './env.js';
import { createLogger, logOperationFields, type Logger } from './logger.js';
import {
  guard,
  initSentry,
  installProcessGuards,
  reportError,
  ServiceUnavailableError,
  UserError,
} from './errors.js';
import { createKv, keys, type Kv } from './redis.js';
import { createSupabase, type TypedSupabase } from './db/supabase.js';
import { connectMongo, connectSecondaryMongo, type LogDoc, type MongoHandle } from './db/mongo.js';
import { createBatchWriter, type LogSink } from './log-sink.js';
import { createEmbedFactory, type EmbedFactory } from './embed.js';
import { QueueTimeoutError, ServiceBusyError, TaskQueue, type QueueOptions } from './queue.js';
import { LazyCommandRunner, UNIVERSAL_COMMANDS_DIR } from './commands.js';
import { startKeepalivePing } from './keepalive.js';
import { attachServerLock, isGuildAuthorized } from './server-lock.js';
import { startHealthServer, type HealthDeps, type HealthServer } from './health.js';
import { DEFAULT_POLICY, enforceRateLimit, type RateLimitPolicy } from './rate-limit.js';
import { replyOrFollowUp } from './responses.js';
import { sanitizeReason, sanitizeText } from './sanitize.js';
import { isBotOperational } from './control.js';
import type { BotControlState, BotServices, ButtonContext, ButtonHandler, CommandContext } from './types.js';
import { BotInterlink } from './interlink.js';
import type { InterlinkEvent } from './interlink.js';
import { writeGuildWhitelist } from './whitelist.js';
import { hydrateRuntimeSecrets } from './vault-client.js';

const AUDIT_SECRET_KEY = /(token|secret|password|private.?key|service.?role|connection.?string|mongodb|redis|supabase|firebase|cloudflare|authorization|cookie)/i;
const DISCORD_TOKEN_PATTERN = /^[A-Za-z0-9_-]{24,}\.[A-Za-z0-9_-]{6}\./;

export type GuildAuthorizationDecision = 'full' | 'temp' | 'deny';

/** Parse only authorization buttons generated by the private review workflow. */
export function parseGuildAuthorizationButton(customId: string): {
  decision: GuildAuthorizationDecision;
  guildId: string;
} | null {
  const match = /^guild-auth:(full|temp|deny):(\d{17,20})$/.exec(customId);
  if (!match) return null;
  const decision = match[1];
  const guildId = match[2];
  if (!decision || !guildId) return null;
  return { decision: decision as GuildAuthorizationDecision, guildId };
}

export function redactAuditMeta(value: Record<string, unknown>): Record<string, unknown> {
  const walk = (input: unknown, depth: number): unknown => {
    if (depth > 4) return '[truncated]';
    if (typeof input === 'string') {
      if (
        /^(?:mongodb(?:\+srv)?|postgres(?:ql)?|redis):\/\//i.test(input) ||
        DISCORD_TOKEN_PATTERN.test(input) ||
        /-----BEGIN .*PRIVATE KEY-----/.test(input)
      ) return '[redacted]';
      return input.slice(0, 512);
    }
    if (Array.isArray(input)) return input.slice(0, 25).map((item) => walk(item, depth + 1));
    if (input && typeof input === 'object') {
      const output: Record<string, unknown> = {};
      for (const [key, child] of Object.entries(input as Record<string, unknown>).slice(0, 50)) {
        output[key] = AUDIT_SECRET_KEY.test(key) ? '[redacted]' : walk(child, depth + 1);
      }
      return output;
    }
    return input;
  };
  const redacted = walk(value, 0) as Record<string, unknown>;
  try {
    if (Buffer.byteLength(JSON.stringify(redacted), 'utf8') > 8 * 1024) return { notice: 'audit metadata truncated' };
  } catch {
    return { notice: 'audit metadata unavailable' };
  }
  return redacted;
}

export interface CreateBotOptions {
  intents: ClientOptions['intents'];
  partials?: ClientOptions['partials'];
  /** Absolute path to this bot's `src/commands` directory. */
  commandsDir: string;
  rateLimit?: RateLimitPolicy;
  queue?: QueueOptions;
  /** Commands exempt from the default limiter (read-only lookups). */
  unlimitedCommands?: string[];
  /**
   * Handler for button interactions this bot owns (pagination, confirmations).
   * Routed through the same authorization, pause, dev-guild and rate-limit
   * gates as a slash command, so a bot never has to reimplement them.
   */
  handleButton?: ButtonHandler;
  /** Wire up extra event listeners before login; optionally return shutdown cleanup. */
  setup?: (ctx: { client: Client; services: BotServices; log: Logger; env: Env }) => void | (() => void | Promise<void>) | Promise<void | (() => void | Promise<void>)>;
}

export interface BotRuntime {
  client: Client;
  env: Env;
  log: Logger;
  services: BotServices;
  shutdown: (signal: string) => Promise<void>;
}

const SHUTDOWN_TIMEOUT_MS = 25_000;

export class StartupCancelledError extends Error {
  override readonly name = 'StartupCancelledError';
}

export function assertStartupActive(shuttingDown: boolean): void {
  if (shuttingDown) throw new StartupCancelledError('startup cancelled by shutdown');
}

export type ShutdownOutcome = 'completed' | 'timed-out';

export function withShutdownTimeout(operation: Promise<void>, timeoutMs: number): Promise<ShutdownOutcome> {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => resolve('timed-out'), timeoutMs);
    timer.unref?.();
    operation.then(
      () => {
        clearTimeout(timer);
        operation.catch(() => undefined);
        resolve('completed');
      },
      (error) => {
        clearTimeout(timer);
        reject(error);
      },
    );
  });
}

export function buildClientOptions(options: Pick<CreateBotOptions, 'intents' | 'partials'>): ClientOptions {
  return {
    intents: options.intents,
    ...(options.partials === undefined ? {} : { partials: options.partials }),
  };
}

async function replyEmbed(
  interaction: ChatInputCommandInteraction,
  embed: EmbedBuilder,
  ephemeral: boolean,
  log: Logger,
): Promise<void> {
  await replyOrFollowUp(interaction, {
    embeds: [embed],
    ephemeral,
  }, log);
}

function buildContext(
  interaction: ChatInputCommandInteraction,
  client: Client,
  services: BotServices,
  commandsDir: string,
): CommandContext {
  const guildId = interaction.guildId ?? 'dm';
  const log = services.log.child({ command: interaction.commandName, guildId, userId: interaction.user.id });

  const send = (embed: EmbedBuilder, ephemeral = false) => replyEmbed(interaction, embed, ephemeral, log);

  const ctx: CommandContext = {
    interaction,
    client,
    services,
    log,
    guildId,
    commandsDir,
    userId: interaction.user.id,

    async defer(ephemeral = false) {
      if (!interaction.deferred && !interaction.replied) {
        await interaction.deferReply({ flags: ephemeral ? MessageFlags.Ephemeral : undefined });
      }
    },

    replyEmbed: (embed, ephemeral = false) => send(embed, ephemeral),
    success: (title, description, ephemeral) => send(services.embeds.success(title, description), ephemeral),
    error: (title, description, ephemeral) => send(services.embeds.error(title, description), ephemeral),
    info: (title, description, ephemeral) => send(services.embeds.info(title, description), ephemeral),
    warn: (title, description, ephemeral) => send(services.embeds.warning(title, description), ephemeral),

    targetUser(): User {
      const user = interaction.options.getUser('user');
      if (!user) throw new UserError('You must specify a target user.');
      return user;
    },

    targetMember(): GuildMember | null {
      const member = interaction.options.getMember('user');
      return (member && 'joinedTimestamp' in member ? member : null) as GuildMember | null;
    },

    stringOption: (name) => {
      const raw = interaction.options.getString(name);
      return raw === null ? null : sanitizeText(raw, 512);
    },

    requiredString(name) {
      const raw = interaction.options.getString(name);
      if (raw === null || sanitizeText(raw).length === 0) {
        throw new UserError(`Missing required option \`${name}\`.`);
      }
      return sanitizeText(raw, 512);
    },

    intOption: (name) => interaction.options.getInteger(name),

    requiredInt(name) {
      const raw = interaction.options.getInteger(name);
      if (raw === null) throw new UserError(`Missing required option \`${name}\`.`);
      return raw;
    },

    reason(fallback) {
      const raw = sanitizeReason(interaction.options.getString('reason') ?? undefined);
      return raw === 'No reason provided' ? (fallback ?? 'No reason provided') : raw;
    },
  };

  return ctx;
}

/**
 * Build a `ButtonContext` from a button interaction. This is the
 * option-less twin of `buildContext`; both share the same reply helpers so
 * command and button code can render failures identically.
 */
function buildButtonContext(
  interaction: ButtonInteraction,
  client: Client,
  services: BotServices,
): ButtonContext {
  const guildId = interaction.guildId ?? 'dm';
  const log = services.log.child({ button: interaction.customId, guildId, userId: interaction.user.id });
  const send = async (embed: EmbedBuilder, ephemeral = false): Promise<void> => {
    await replyOrFollowUp(interaction, { embeds: [embed], ephemeral }, log);
  };

  return {
    interaction,
    client,
    services,
    log,
    guildId,
    userId: interaction.user.id,

    async defer(ephemeral = false) {
      if (!interaction.deferred && !interaction.replied) {
        await interaction.deferReply({ flags: ephemeral ? MessageFlags.Ephemeral : undefined });
      }
    },

    replyEmbed: (embed, ephemeral = false) => send(embed, ephemeral),
    success: (title, description, ephemeral) => send(services.embeds.success(title, description), ephemeral),
    error: (title, description, ephemeral) => send(services.embeds.error(title, description), ephemeral),
    info: (title, description, ephemeral) => send(services.embeds.info(title, description), ephemeral),
    warn: (title, description, ephemeral) => send(services.embeds.warning(title, description), ephemeral),
  };
}

async function renderFailure(ctx: CommandContext, err: Error): Promise<void> {
  if (err instanceof ServiceUnavailableError) {
    await ctx.replyEmbed(ctx.services.embeds.unavailable(err.service));
    return;
  }
  // Queue pressure is an expected overload condition, not a defect — it must
  // never reach Sentry as an unhandled error.
  if (err instanceof QueueTimeoutError) {
    await ctx.warn('Timed out', 'That request took too long to complete. Please try again.');
    return;
  }
  if (err instanceof ServiceBusyError) {
    await ctx.warn('Service busy', 'Too many requests are queued. Try again in a moment.');
    return;
  }
  if (err instanceof UserError) {
    await ctx.error('Request failed', err.message);
    return;
  }
  await ctx.error('Unexpected error', 'This has been reported automatically. Please try again shortly.');
}

/** `renderFailure` for button contexts — identical failure rendering. */
async function renderButtonFailure(ctx: ButtonContext, err: Error): Promise<void> {
  if (err instanceof ServiceUnavailableError) {
    await ctx.replyEmbed(ctx.services.embeds.unavailable(err.service));
    return;
  }
  if (err instanceof QueueTimeoutError) {
    await ctx.warn('Timed out', 'That request took too long to complete. Please try again.');
    return;
  }
  if (err instanceof ServiceBusyError) {
    await ctx.warn('Service busy', 'Too many requests are queued. Try again in a moment.');
    return;
  }
  if (err instanceof UserError) {
    await ctx.error('Request failed', err.message);
    return;
  }
  await ctx.error('Unexpected error', 'This has been reported automatically. Please try again shortly.');
}

function boundedString(value: unknown, max: number): string | null {
  return typeof value === 'string' && value.trim().length > 0 ? value.trim().slice(0, max) : null;
}

function safeUrl(value: unknown): string | null {
  const raw = boundedString(value, 2048);
  if (!raw) return null;
  try {
    const parsed = new URL(raw);
    return parsed.protocol === 'https:' || parsed.protocol === 'http:' ? parsed.toString() : null;
  } catch {
    return null;
  }
}

function hexColor(value: unknown): number | null {
  const raw = typeof value === 'string' ? value.trim().replace(/^#/, '') : '';
  return /^[0-9a-f]{6}$/i.test(raw) ? Number.parseInt(raw, 16) : null;
}

export function buildDashboardEmbed(payload: Record<string, unknown>): {
  embed: EmbedBuilder;
  components: ActionRowBuilder<ButtonBuilder>[];
} | null {
  const embed = new EmbedBuilder();
  const title = boundedString(payload.title, 256);
  const description = boundedString(payload.description, 4096);
  const url = safeUrl(payload.url);
  const color = hexColor(payload.color);
  const footer = boundedString(payload.footer, 2048);
  const thumbnail = safeUrl(payload.thumbnail);
  const image = safeUrl(payload.image);
  const author = payload.author && typeof payload.author === 'object' && !Array.isArray(payload.author)
    ? payload.author as Record<string, unknown>
    : null;

  if (title) embed.setTitle(title);
  if (description) embed.setDescription(description);
  if (url) embed.setURL(url);
  if (color !== null) embed.setColor(color);
  if (footer) embed.setFooter({ text: footer });
  if (thumbnail) embed.setThumbnail(thumbnail);
  if (image) embed.setImage(image);
  if (author) {
    const name = boundedString(author.name, 256);
    if (name) {
      embed.setAuthor({ name, url: safeUrl(author.url) ?? undefined, iconURL: safeUrl(author.iconUrl) ?? undefined });
    }
  }

  const fields: APIEmbedField[] = [];
  if (Array.isArray(payload.fields)) {
    for (const rawField of payload.fields.slice(0, 25)) {
      if (!rawField || typeof rawField !== 'object' || Array.isArray(rawField)) continue;
      const field = rawField as Record<string, unknown>;
      const name = boundedString(field.name, 256);
      const value = boundedString(field.value, 1024);
      if (name && value) fields.push({ name, value, inline: field.inline === true });
    }
  }
  if (fields.length > 0) embed.addFields(fields);
  const hasContent = Boolean(title || description || url || footer || thumbnail || image || author?.name) || fields.length > 0;
  if (!hasContent) return null;

  const buttons: ButtonBuilder[] = [];
  if (Array.isArray(payload.buttons)) {
    for (const rawButton of payload.buttons.slice(0, 5)) {
      if (!rawButton || typeof rawButton !== 'object' || Array.isArray(rawButton)) continue;
      const button = rawButton as Record<string, unknown>;
      const label = boundedString(button.label, 80);
      const buttonUrl = safeUrl(button.url);
      if (label && buttonUrl) {
        buttons.push(new ButtonBuilder().setLabel(label).setStyle(ButtonStyle.Link).setURL(buttonUrl));
      }
    }
  }

  return {
    embed,
    components: buttons.length > 0 ? [new ActionRowBuilder<ButtonBuilder>().addComponents(buttons)] : [],
  };
}

export async function handleDashboardEmbed(
  client: Client,
  event: InterlinkEvent,
  log: Logger,
  isAuthorized: (guildId: string) => Promise<boolean>,
  isOperational: (guildId: string) => Promise<boolean>,
): Promise<void> {
  if (event.type !== 'dashboard.send_embed' || !event.guildId) return;
  if (!(await isAuthorized(event.guildId))) {
    log.warn({ guildId: event.guildId }, 'dashboard embed rejected for unauthorized guild');
    return;
  }
  if (!(await isOperational(event.guildId))) {
    log.warn({ guildId: event.guildId }, 'dashboard embed rejected for paused guild');
    return;
  }
  const channelId = boundedString(event.payload.channelId, 32);
  if (!channelId || !/^\d{17,20}$/.test(channelId)) return;

  let channel;
  try {
    channel = await client.channels.fetch(channelId);
  } catch (error) {
    if (error instanceof DiscordAPIError && error.code === 10003) {
      log.warn({ guildId: event.guildId, channelId }, 'dashboard embed dropped because channel no longer exists');
      return;
    }
    throw error;
  }
  if (!channel || channel.isDMBased() || !('guild' in channel) || channel.guild?.id !== event.guildId || !('send' in channel)) {
    log.warn({ guildId: event.guildId, channelId }, 'dashboard embed channel rejected');
    return;
  }

  const built = buildDashboardEmbed(event.payload);
  if (!built) return;
  await channel.send({ embeds: [built.embed], components: built.components, allowedMentions: { parse: [] } });
}

export async function createBot(options: CreateBotOptions): Promise<BotRuntime> {
  const startedAt = Date.now();
  let shutdownRequested = false;
  let teardownStarted = false;
  let teardownComplete: Promise<void> | null = null;
  const onStartupSignal = (): void => {
    shutdownRequested = true;
  };
  process.once('SIGTERM', onStartupSignal);
  process.once('SIGINT', onStartupSignal);

  // Validate explicit bootstrap values, especially DISCORD_TOKEN, before any
  // optional vault work. The health server binds from this immutable snapshot;
  // the final environment is loaded only after hydration has settled.
  const bootstrapEnv = loadEnv();
  const bootstrapLog = createLogger(bootstrapEnv);
  const server: HealthServer = await startHealthServer({
    port: bootstrapEnv.port,
    host: ['true', '1', 'yes'].includes(process.env.LOCAL_ONLY?.trim().toLowerCase() ?? '') ? '127.0.0.1' : undefined,
    botId: bootstrapEnv.botId,
    version: bootstrapEnv.botVersion,
    startedAt,
    log: bootstrapLog,
  });

  try {
    const hydration = await hydrateRuntimeSecrets({ botId: bootstrapEnv.botId });
    if (hydration.missing.length || hydration.failed.length) {
      bootstrapLog.warn(
        { missing: hydration.missing, failed: hydration.failed },
        'optional vault hydration incomplete; continuing degraded',
      );
    }
  } catch (error) {
    bootstrapLog.warn({ err: error }, 'optional vault hydration failed; continuing degraded');
  }

  // loadEnv memoizes its result, so discard the bootstrap snapshot before
  // constructing clients that consume newly hydrated optional credentials.
  resetEnvCache();
  const env = loadEnv();
  const log = createLogger(env);

  initSentry(env);
  installProcessGuards(env.botId, log);

  const supabase: TypedSupabase | null = createSupabase(env);
  const kv: Kv = createKv(env);
  const embeds: EmbedFactory = createEmbedFactory(env);
  const queue = new TaskQueue(options.queue ?? { concurrency: 2, timeoutMs: 15_000 });

  // Declared but NOT awaited here: the health server must bind the port first.
  // Both sinks and `getMongo` read these lazily, so nothing observes a
  // half-initialised handle — see the connect step below.
  let mongoHandle: MongoHandle | null = null;
  let secondaryMongoHandle: MongoHandle | null = null;
  const interlink = new BotInterlink(kv, env.botId);
  const controlCache = new Map<string, { state: BotControlState; expiresAt: number }>();
  const cacheControlState = (guildId: string, state: BotControlState): void => {
    controlCache.set(guildId, { state, expiresAt: Date.now() + 15_000 });
    if (controlCache.size <= 10_000) return;
    const now = Date.now();
    for (const [key, value] of controlCache) {
      if (value.expiresAt <= now) controlCache.delete(key);
    }
  };

  /* Batched log writer — the main defence against blowing the Mongo write cap. */
  let writeCount = 0;
  let writeWindowStart = Date.now();

  /* --- health + uptime --------------------------------------------------- *
   * The port is opened before vault and database work. Render can therefore
   * observe process liveness while optional integrations recover.
   * --------------------------------------------------------------------- */
  const healthDeps: HealthDeps = {
    env,
    log,
    startedAt,
    kv,
    supabase,
    getMongo: () => mongoHandle,
    queue,
    writes1h: () => {
      if (Date.now() - writeWindowStart > 3_600_000) {
        writeWindowStart = Date.now();
        writeCount = 0;
      }
      return writeCount;
    },
  };
  server.setDependencies(healthDeps);

  // Port is live, so blocking database connects are now safe to run.
  const [primaryMongo, secondaryMongo] = await Promise.all([
    connectMongo(env, log),
    connectSecondaryMongo(env, log),
  ]);
  mongoHandle = primaryMongo;
  secondaryMongoHandle = secondaryMongo;

  const baseSink = createBatchWriter<LogDoc>({
    getCollection: () => mongoHandle?.collections.logs ?? null,
    intervalMs: 30_000,
    maxBatch: 200,
    maxBuffered: 5_000,
    onDrop: (dropped) => {
      log.warn({ dropped }, 'primary audit log buffer capped; dropping oldest entries');
    },
    onError: (err, dropped) => {
      const failedHandle = mongoHandle;
      mongoHandle = null;
      void failedHandle?.client.close().catch(() => undefined);
      log.error({ err, dropped }, 'log batch write failed; reconnecting primary Mongo');
      reportError(err, { botId: env.botId });
    },
  });
  const backupSink = createBatchWriter<LogDoc>({
    getCollection: () => secondaryMongoHandle?.collections.logs ?? null,
    intervalMs: 30_000,
    maxBatch: 200,
    maxBuffered: 5_000,
    onDrop: (dropped) => {
      log.warn({ dropped }, 'secondary audit log buffer capped; dropping oldest entries');
    },
    onError: (err, dropped) => {
      // Backup failure must never interrupt primary bot operation. Mark the
      // handle unavailable so the reconnect loop can establish a fresh sink.
      const failedHandle = secondaryMongoHandle;
      secondaryMongoHandle = null;
      void failedHandle?.client.close().catch(() => undefined);
      log.warn({ err, dropped }, 'secondary audit log batch failed; reconnecting');
    },
  });

  const logs: LogSink = {
    push(doc) {
      writeCount += 1;
      const safeDoc = { ...doc, meta: redactAuditMeta(doc.meta) };
      baseSink.push(safeDoc);
      backupSink.push(safeDoc);
    },
    async flush() {
      await Promise.all([baseSink.flush(), backupSink.flush()]);
    },
    async stop() {
      await Promise.all([baseSink.stop(), backupSink.stop()]);
    },
    stats: () => ({
      buffered: baseSink.stats().buffered + backupSink.stats().buffered,
      dropped: baseSink.stats().dropped + backupSink.stats().dropped,
      flushed: baseSink.stats().flushed + backupSink.stats().flushed,
      failed: baseSink.stats().failed + backupSink.stats().failed,
    }),
  };

  const services: BotServices = {
    env,
    log,
    supabase,
    redis: kv,
    embeds,
    queue,
    logs,
    async mongo() {
      return mongoHandle?.collections ?? null;
    },
    async requireMongo() {
      if (!mongoHandle) throw new ServiceUnavailableError('Database');
      return mongoHandle.collections;
    },
    requireSupabase() {
      if (!supabase) throw new ServiceUnavailableError('Database');
      return supabase;
    },
    isAuthorized: (guildId) => isGuildAuthorized(supabase, guildId, env, kv),
    interlink,
    async getControlState(guildId) {
      const cached = controlCache.get(guildId);
      if (cached && cached.expiresAt > Date.now()) return cached.state;
      const fallback: BotControlState = {
        enabled: true,
        paused: false,
        serverPaused: false,
        featureFlags: {},
      };
      if (!supabase) return fallback;
      const [settings, botState] = await Promise.all([
        supabase.from('server_settings').select('server_paused').eq('guild_id', guildId).maybeSingle(),
        supabase.from('bot_states').select('enabled,paused,feature_flags').eq('guild_id', guildId).eq('bot_id', env.botId).maybeSingle(),
      ]);
      if (settings.error || botState.error) {
        const blocked = { ...fallback, enabled: false, paused: true, serverPaused: true };
        cacheControlState(guildId, blocked);
        return blocked;
      }
      const state: BotControlState = {
        enabled: botState.data?.enabled ?? true,
        paused: botState.data?.paused ?? false,
        serverPaused: settings.data?.server_paused ?? false,
        featureFlags: (botState.data?.feature_flags as Record<string, unknown> | null) ?? {},
      };
      cacheControlState(guildId, state);
      return state;
    },
    isOwner: (userId) => env.ownerIds.includes(userId),
  };

  const client = new Client(buildClientOptions(options));
  const stopInterlink = interlink.startPolling((event) =>
    handleDashboardEmbed(
      client,
      event,
      log,
      (guildId) => isGuildAuthorized(supabase, guildId, env, kv),
      async (guildId) => isBotOperational(await services.getControlState(guildId)),
    ),
  );
  // Bot-specific handlers first; the shared universal commands are the fallback
  // so a bot can override /help or /about by defining its own.
  const runner = new LazyCommandRunner([options.commandsDir, UNIVERSAL_COMMANDS_DIR]);
  const unlimited = new Set(options.unlimitedCommands ?? []);

  /* --- server lock ------------------------------------------------------ */
  const stopServerLock = attachServerLock(client, {
    env,
    log,
    supabase,
    record: ({ action, level, message, guildId, meta }) => {
      logs.push({
        bot_id: env.botId,
        guild_id: guildId ?? null,
        channel_id: null,
        user_id: null,
        action,
        level,
        message,
        meta: meta ?? {},
        created_at: new Date(),
      });
    },
  });

  /* --- command dispatch -------------------------------------------------- */
  client.on(Events.InteractionCreate, async (interaction) => {
    if (interaction.isButton()) {
      if (!interaction.customId.startsWith('guild-auth:')) {
        // Bot-owned buttons (pagination, confirmations). The handler decides
        // whether it recognizes the customId; unknown buttons are ignored.
        if (!options.handleButton) return;
        const buttonCtx = buildButtonContext(interaction, client, services);
        const requestId = randomUUID();
        const startedAt = Date.now();
        const baseOperation = {
          command: `button:${interaction.customId.slice(0, 32)}`,
          ...logOperationFields({ guildId: buttonCtx.guildId, requestId }),
        };
        const finishOperation = (status: string, errorClass?: string): void => {
          log.info(
            {
              ...baseOperation,
              ...logOperationFields({
                guildId: buttonCtx.guildId,
                requestId,
                latencyMs: Date.now() - startedAt,
                status,
                errorClass,
              }),
            },
            'button operation completed',
          );
        };
        try {
          if (buttonCtx.guildId !== 'dm' && !(await services.isAuthorized(buttonCtx.guildId))) {
            await buttonCtx.error('Not authorized', 'This server is not enabled for this bot.');
            finishOperation('unauthorized');
            return;
          }
          if (buttonCtx.guildId !== 'dm') {
            const state = await services.getControlState(buttonCtx.guildId);
            if (!state.enabled || state.paused || state.serverPaused) {
              await buttonCtx.warn('Bot paused', 'This bot is currently paused for this server.');
              finishOperation('paused');
              return;
            }
            if (buttonCtx.guildId === env.devGuildId && interaction.user.id !== env.masterDiscordId) {
              await buttonCtx.error(
                'Development server restricted',
                'Only the master operator can use commands in the development server.',
                true,
              );
              finishOperation('dev_operator_only');
              return;
            }
          }
          const verdict = await enforceRateLimit(
            kv,
            keys.rateLimit(env.botId, buttonCtx.guildId, interaction.user.id, 'button'),
            { limit: 30, windowSec: (options.rateLimit ?? DEFAULT_POLICY).windowSec },
            services.isOwner(interaction.user.id),
          );
          if (!verdict.allowed) {
            await buttonCtx.warn('Slow down', `You can do that again in ${verdict.retryAfterSec}s.`);
            finishOperation('rate_limited');
            return;
          }

          const result = await guard(
            'button',
            () => options.handleButton!(buttonCtx),
            { botId: env.botId, command: 'button', guildId: buttonCtx.guildId, userId: interaction.user.id },
          );
          if (!result.ok) {
            await renderButtonFailure(buttonCtx, result.error);
            finishOperation(result.expected ? 'expected_failure' : 'unexpected_failure', result.error.name);
          } else {
            finishOperation(result.value ? 'ok' : 'ignored');
          }
        } catch (err) {
          log.error({ ...baseOperation, err }, 'unhandled button error');
          await buttonCtx
            .error('Unexpected error', 'This has been reported automatically. Please try again shortly.')
            .catch(() => undefined);
        }
        return;
      }
      try {
        const masterDiscordId = env.masterDiscordId;
        if (!masterDiscordId || interaction.user.id !== masterDiscordId) {
          await interaction.reply({ content: 'Only the master operator can approve guilds.', flags: MessageFlags.Ephemeral }).catch(() => undefined);
          return;
        }
        const authorization = parseGuildAuthorizationButton(interaction.customId);
        const reviewChannelConfigured = Boolean(env.devGuildId && env.devAuthChannelId);
        const messageAuthorId = interaction.message.author?.id ?? null;
        if (
          !reviewChannelConfigured ||
          interaction.guildId !== env.devGuildId ||
          interaction.channelId !== env.devAuthChannelId ||
          messageAuthorId !== client.user?.id ||
          !authorization
        ) {
          await interaction.reply({ content: 'This authorization control is invalid or expired.', flags: MessageFlags.Ephemeral }).catch(() => undefined);
          return;
        }
        if (!supabase) {
          await interaction.reply({ content: 'Authorization storage is unavailable.', flags: MessageFlags.Ephemeral }).catch(() => undefined);
          return;
        }
        const { decision, guildId } = authorization;
        const type = decision === 'deny' ? 'unauthorised' : decision;
        const expiresAt = decision === 'temp' ? new Date(Date.now() + 24 * 60 * 60_000).toISOString() : null;
        await writeGuildWhitelist(supabase, { guildId, type: type as 'full' | 'temp' | 'unauthorised', expiresAt, kv });
        await interaction.update({ components: [], content: `Authorization decision: ${decision === 'deny' ? 'denied' : decision === 'temp' ? 'temporary 24h' : 'full access'}` });
      } catch (error) {
        log.error({ err: error }, 'guild authorization button handler failed');
        await interaction.reply({ content: 'The authorization decision could not be saved.', flags: MessageFlags.Ephemeral }).catch(() => undefined);
      }
      return;
    }
    if (!interaction.isChatInputCommand()) return;

    const name = interaction.commandName;
    const guildId = interaction.guildId ?? 'dm';
    const ctx = buildContext(interaction, client, services, options.commandsDir);
    const requestId = randomUUID();
    const startedAt = Date.now();
    const baseOperation = { command: name, ...logOperationFields({ guildId, requestId }) };
    const finishOperation = (status: string, errorClass?: string): void => {
      log.info({
        ...baseOperation,
        ...logOperationFields({
          guildId,
          requestId,
          latencyMs: Date.now() - startedAt,
          status,
          errorClass,
        }),
      }, 'command operation completed');
    };

    try {
      if (guildId !== 'dm' && !(await services.isAuthorized(guildId))) {
        await ctx.error('Not authorized', 'This server is not enabled for this bot.');
        finishOperation('unauthorized');
        return;
      }

      if (guildId !== 'dm') {
        const state = await services.getControlState(guildId);
        if (!state.enabled || state.paused || state.serverPaused) {
          await ctx.warn('Bot paused', 'This bot is currently paused for this server.');
          finishOperation('paused');
          return;
        }

        // The development guild is an operator-only control plane. This gate
        // applies before command-specific authorization and rate limiting so a
        // non-master never receives a misleading cooldown response or consumes
        // a limiter bucket by repeatedly probing operator commands.
        if (guildId === env.devGuildId && interaction.user.id !== env.masterDiscordId) {
          await ctx.error('Development server restricted', 'Only the master operator can use commands in the development server.', true);
          finishOperation('dev_operator_only');
          return;
        }

        // Dev-only commands (authorization and other operator controls) are
        // guild-scoped to DEV_GUILD_ID at registration; this runtime check is
        // the second layer in case a stale scope lingers anywhere.
        if ((await runner.accessFor(name)) === 'dev' && guildId !== env.devGuildId) {
          await ctx.error('Dev server only', 'This command is restricted to the operator development server.');
          finishOperation('dev_only');
          return;
        }

        // Dashboard-configurable RBAC: per-guild, per-command Discord role
        // allowlists stored in bot_states.feature_flags.command_roles.
        // Owners, administrators, and operators always pass.
        const commandRoles = (state.featureFlags as { command_roles?: unknown }).command_roles;
        if (guildId !== 'dm' && commandRoles && typeof commandRoles === 'object' && !Array.isArray(commandRoles)) {
          const allowed = (commandRoles as Record<string, unknown>)[name];
          if (Array.isArray(allowed) && allowed.length > 0 && typeof allowed[0] === 'string') {
            const bypass =
              services.isOwner(interaction.user.id) ||
              interaction.user.id === interaction.guild?.ownerId ||
              new PermissionsBitField(
                (interaction.member as GuildMember | null)?.permissions ?? 0n,
              ).has(PermissionsBitField.Flags.Administrator);
            if (!bypass) {
              const memberRoles = interaction.inGuild() ? interaction.member?.roles : null;
              const hasRole =
                memberRoles && 'cache' in memberRoles
                  ? (allowed as string[]).some((roleId) => memberRoles.cache.has(roleId))
                  : false;
              if (!hasRole) {
                await ctx.error('Restricted command', 'Your roles do not allow this command in this server.');
                finishOperation('forbidden');
                return;
              }
            }
          }
        }
      }

      const policy = unlimited.has(name)
        ? { limit: 30, windowSec: (options.rateLimit ?? DEFAULT_POLICY).windowSec }
        : (options.rateLimit ?? DEFAULT_POLICY);
      const verdict = await enforceRateLimit(
        kv,
        keys.rateLimit(env.botId, guildId, interaction.user.id, name),
        policy,
        services.isOwner(interaction.user.id),
      );
      if (!verdict.allowed) {
        await ctx.warn('Slow down', `You can use this command again in ${verdict.retryAfterSec}s.`);
        finishOperation('rate_limited');
        return;
      }

      const result = await guard(
        name,
        () => runner.execute(name, ctx),
        { botId: env.botId, command: name, guildId, userId: interaction.user.id },
      );

      if (!result.ok) {
        await renderFailure(ctx, result.error);
        finishOperation(result.expected ? 'expected_failure' : 'unexpected_failure', result.error.name);
      } else {
        finishOperation('ok');
      }
    } catch (err) {
      // Last-resort net: nothing escapes into the gateway.
      log.error({
        ...baseOperation,
        ...logOperationFields({
          guildId,
          requestId,
          latencyMs: Date.now() - startedAt,
          status: 'handler_failed',
          errorClass: err instanceof Error ? err.name : 'UnknownError',
        }),
        err,
      }, 'interaction handler crashed');
      reportError(err, { botId: env.botId, command: name, guildId });
    }
  });

  let heartbeatTimer: NodeJS.Timeout | null = null;
  client.on(Events.ClientReady, (ready) => {
    const refreshHeartbeat = (): void => {
      void interlink.heartbeat(ready.guilds.cache.size).catch((err) => {
        log.warn({ err }, 'interlink heartbeat failed');
      });
    };
    refreshHeartbeat();
    if (heartbeatTimer) clearInterval(heartbeatTimer);
    heartbeatTimer = setInterval(refreshHeartbeat, 60_000);
    heartbeatTimer.unref?.();
    startKeepalivePing(env, log);
    log.info(
      { guilds: ready.guilds.cache.size, user: ready.user.tag, commands: options.commandsDir },
      'bot ready',
    );
  });

  client.on(Events.Error, (err) => {
    log.error({ err }, 'discord client error');
    reportError(err, { botId: env.botId });
  });

  let setupCleanup: (() => void | Promise<void>) | undefined;

  /* --- Mongo auto-reconnect --------------------------------------------- */
  const reconnecting = new Set<Promise<void>>();
  const reconnectInFlight = new Set<'primary' | 'secondary'>();
  const launchReconnect = (
    slot: 'primary' | 'secondary',
    connect: () => Promise<MongoHandle | null>,
    assign: (handle: MongoHandle) => void,
    label: string,
  ): void => {
    if (reconnectInFlight.has(slot)) return;
    reconnectInFlight.add(slot);
    const pending = connect()
      .then(async (handle) => {
        if (!handle) return;
        if (shutdownRequested) {
          await handle.client.close().catch((err) => log.error({ err }, `${label} Mongo shutdown failed`));
          return;
        }
        const previous = slot === 'primary' ? mongoHandle : secondaryMongoHandle;
        if (previous && previous !== handle) {
          await previous.client.close().catch(() => undefined);
        }
        assign(handle);
        log.info(`${label} mongodb reconnected`);
      })
      .catch((err) => log.error({ err }, `${label} mongodb reconnect failed`))
      .finally(() => reconnectInFlight.delete(slot));
    reconnecting.add(pending);
    void pending.finally(() => reconnecting.delete(pending));
  };
  const reconnect = setInterval(() => {
    if (shutdownRequested) return;
    if (!mongoHandle) launchReconnect('primary', () => connectMongo(env, log), (handle) => { mongoHandle = handle; }, 'primary');
    if (!secondaryMongoHandle) launchReconnect('secondary', () => connectSecondaryMongo(env, log), (handle) => { secondaryMongoHandle = handle; }, 'secondary');
  }, 60_000);
  reconnect.unref?.();

  /* --- graceful shutdown ------------------------------------------------- */
  const runTeardown = async (signal: string): Promise<void> => {
    shutdownRequested = true;
    log.info({ signal }, 'shutting down');

    const timedOut = await withShutdownTimeout((async () => {
      clearInterval(reconnect);
      if (heartbeatTimer) clearInterval(heartbeatTimer);
      heartbeatTimer = null;
      stopInterlink();
      stopServerLock();
      await new Promise<void>((resolve) => {
        server.close((err) => {
          if (err) log.error({ err }, 'health server shutdown failed');
          resolve();
        });
      });
      client.destroy();
      await Promise.all([...reconnecting]);
      let cleanupError: unknown;
      try {
        if (typeof setupCleanup === 'function') await setupCleanup();
      } catch (err) {
        cleanupError = err;
        log.error({ err }, 'bot-specific shutdown cleanup failed');
      } finally {
        await baseSink.stop().catch((err) => log.error({ err }, 'base log sink shutdown failed'));
        await backupSink.stop().catch((err) => log.error({ err }, 'backup log sink shutdown failed'));
        await mongoHandle?.client.close().catch((err) => log.error({ err }, 'primary Mongo shutdown failed'));
        await secondaryMongoHandle?.client.close().catch((err) => log.error({ err }, 'secondary Mongo shutdown failed'));
      }
      if (cleanupError) throw cleanupError;
    })(), SHUTDOWN_TIMEOUT_MS).catch((err) => {
      log.error({ err }, 'shutdown cleanup failed');
      return false;
    });

    if (timedOut) {
      log.error({ timeoutMs: SHUTDOWN_TIMEOUT_MS }, 'shutdown timed out; forcing process exit');
      process.exit(1);
    }
    log.info('shutdown complete');
  };

  const shutdown = async (signal: string): Promise<void> => {
    shutdownRequested = true;
    if (teardownComplete) return teardownComplete;
    if (teardownStarted) return;
    teardownStarted = true;
    teardownComplete = runTeardown(signal);
    return teardownComplete;
  };

  process.removeListener('SIGTERM', onStartupSignal);
  process.removeListener('SIGINT', onStartupSignal);
  process.once('SIGTERM', () => void shutdown('SIGTERM'));
  process.once('SIGINT', () => void shutdown('SIGINT'));

  try {
    assertStartupActive(shutdownRequested);
    const cleanup = await options.setup?.({ client, services, log, env });
    setupCleanup = typeof cleanup === 'function' ? cleanup : undefined;
    assertStartupActive(shutdownRequested);
    await client.login(env.discordToken);
  } catch (err) {
    // Bootstrap failure: drive the normal teardown so the log buffers holding
    // the failure diagnostics are flushed before the process exits.
    await shutdown('BOOTSTRAP_FAIL');
    if (err instanceof StartupCancelledError) process.exit(0);
    throw err;
  }

  return { client, env, log, services, shutdown };
}

export type { Env, Logger };
